// import { ThemeProvider } from "@/components/ThemeContext";
import { ThemeToggle } from "@/components/ThemeToggle";
import { Providers, AuthProvider } from "./providers"; // sau unde ai pus Providers
import { NavbarWrapper } from "@/components/navbar-wrapper";
import type { Metadata } from "next";
import "./globals.css";
import { Orbitron } from "next/font/google";

export const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${orbitron.variable}`}>
        <Providers>
          <AuthProvider>
            <NavbarWrapper />
            <main className="w-full pt-16 md:pt-20">{children}</main>
            <div className="fixed bottom-4 right-4">
              <ThemeToggle />
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
